Fix tox for releasenotes
tox -e releasenotes fails with error:
ImportError: No module named 'masakaridashboard'.

Since release notes are version independent, no need to set version
and release so removed importing version from masakaridashboard.

Change-Id: I2ef95fa2c938e2a8115c0602b53c5af6329a1bac